apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-tracking-service
spec:
  replicas: 2   # Number of desired replicas
  selector:
    matchLabels:
      app: price-tracking-service
  template:
    metadata:
      labels:
        app: price-tracking-service
    spec:
      containers:
        - name: price-tracking-service
          image: ${DOCKER_USERNAME}/price-tracking-service:latest
          ports:
            - containerPort: 8080
